### ISSUE TITLE
Use GoCD's official URLs in repo.sls

### ISSUE THREAD

**Issue by blast-hardcheese** [corux/gocd-formula#1]
The work you've put into this repo is amazing, just wondering why you chose to use bintray directly instead of the URL described on GoCD's download page: https://www.go.cd/download/ . Guessing predictability or reliability?

**Comment by corux** [comment]
Thanks for noticing the difference in repo.sls and the official GoCD yum repo install instruction.
The URL changed with GoCD 16.1.0. Previously bintray was specified in the official docs.

I've updated the formula accordingly.
